/**
 * @fileoverview gRPC-Web generated client stub for paraformer
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v3.19.4
// source: paraformer.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.paraformer = require('./paraformer_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.paraformer.ASRClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.paraformer.ASRPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.paraformer.Request,
 *   !proto.paraformer.Response>}
 */
const methodDescriptor_ASR_RecognizeStreamResp = new grpc.web.MethodDescriptor(
  '/paraformer.ASR/RecognizeStreamResp',
  grpc.web.MethodType.UNARY,
  proto.paraformer.Request,
  proto.paraformer.Response,
  /**
   * @param {!proto.paraformer.Request} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.paraformer.Response.deserializeBinary
);


/**
 * @param {!proto.paraformer.Request} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.paraformer.Response)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.paraformer.Response>|undefined}
 *     The XHR Node Readable Stream
 */
proto.paraformer.ASRClient.prototype.recognizeStreamResp =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/paraformer.ASR/RecognizeStreamResp',
      request,
      metadata || {},
      methodDescriptor_ASR_RecognizeStreamResp,
      callback);
};


/**
 * @param {!proto.paraformer.Request} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.paraformer.Response>}
 *     Promise that resolves to the response
 */
proto.paraformer.ASRPromiseClient.prototype.recognizeStreamResp =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/paraformer.ASR/RecognizeStreamResp',
      request,
      metadata || {},
      methodDescriptor_ASR_RecognizeStreamResp);
};


module.exports = proto.paraformer;

